version: "3.8"
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null
    ports:
      - "5001:5000"
